### ISSUE TITLE
Country selection doesn't work properly

### ISSUE THREAD

**Issue by sedrakk** [aslushnikov/been#1]
Safari Version 12.1.1 (14607.2.6.1.1)

STR:
1. Open the map
2. Click on a country from the left side bar
3. Scroll the list of countries and click again on any country

See https://drive.google.com/file/d/1-yQvR3iDL2TIfSLXbIuL_4FSAvKIZ9ph/view

**Comment by aslushnikov** [comment]
@sedrakk Thanks for filing! ❤️ This is a webkit bug with CSS Grids.

The bad news is that I failed to come up with a simple workaround in a few hours of fiddling with this.

The good news is that it's been fixed in WebKit upstream and things work fine in the upcoming Safari version. So I prefer waiting for a few months until the next Safari is released and mitigates the issue.
